### ISSUE TITLE
Add support for Visual Studio 2022

### ISSUE THREAD

**Issue by georgeemr** [twilio-labs/NgrokExtensions#47]

**Comment by TanvirArjel** [comment]
It would be great if the Visual Studio 2022 support is added soon.

**Comment by Pckmule** [comment]
Agreed, this would be great to have ASAP! 

P.S. @dprothero thanks for all effort put into this extension BTW. It's been a really useful utility.

**Comment by YamamotoKansuke** [comment]
Would be great if this was available for VS 2022!

**Comment by dprothero** [comment]
Hey folks, sorry for the delay on this. It pains me to say this isn't a project I'm able to actively maintain. I'd be happy to hand it over to someone interested in maintaining it going forward.

**Comment by timheuer** [comment]
Here's a VS2022 'works on my machine' build of the VSIX - https://github.com/timheuer/NgrokExtensions/actions/runs/1685207128 (artifact download has the vsix)

**Comment by des2k7** [comment]
> Here's a VS2022 'works on my machine' build of the VSIX - https://github.com/timheuer/NgrokExtensions/actions/runs/1685207128 (artifact download has the vsix)

thanks a million! works fine on my VS2022 win11 with Basic and free plan :)

**Comment by jbw716** [comment]
> Here's a VS2022 'works on my machine' build of the VSIX - https://github.com/timheuer/NgrokExtensions/actions/runs/1685207128 (artifact download has the vsix)

Thank you so much for this! I really didn't want to have to go back to having to enter my full ngrok command with the port and subdomain manually. This extension speeds up my workflow a whole lot.

This is working great for me with VS Professional 2022. 👍

**Comment by timheuer** [comment]
@jkatsiotis -- retention is only 90 days on artifacts...I re-ran the build and updated artifact here.  I'm trying NOT to publish a version here to override the official one. https://github.com/timheuer/NgrokExtensions/actions/runs/2530153771

**Comment by jayaraut** [comment]
@timheuer Can you please build it again?

**Comment by timheuer** [comment]
> @timheuer i installed the artefact from latest build ([timheuer/NgrokExtensions/actions/runs/2530153771](https://github.com/timheuer/NgrokExtensions/actions/runs/2530153771))
> 
> when i am trying to start the tunnel, getting this error.
> 
> ![image](https://user-images.githubusercontent.com/16084315/187169678-860cfcc5-0c6d-468d-beb4-f2d3477e65f3.png)

Are you on the right version of VS? Latest version?

**Comment by Swimburger** [comment]
Extension added at Extension published at https://marketplace.visualstudio.com/items?itemName=DavidProthero.ngrokextensions-2022
